(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,c="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,e=function(){for(var b,f=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],c=0,k=f.length,d={};c<k;c++)if((b=f[c])&&b[1]in a){for(c=0;c<b.length;c++)d[f[0][c]]=
b[c];return d}return!1}(),g={change:e.fullscreenchange,error:e.fullscreenerror},h={request:function(b){var f=e.requestFullscreen;b=b||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))b[f]();else b[f](c&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[e.exitFullscreen]()},toggle:function(b){this.isFullscreen?this.exit():this.request(b)},onchange:function(b){this.on("change",b)},onerror:function(b){this.on("error",b)},on:function(b,f){var c=g[b];c&&a.addEventListener(c,f,!1)},off:function(b,
f){var c=g[b];c&&a.removeEventListener(c,f,!1)},raw:e};e?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!a[e.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[e.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!a[e.fullscreenEnabled]}}}),d?module.exports=h:window.screenfull=h):d?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),c=window.document,e=c.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var g=c.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var h=c.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+d+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";g.appendChild(h);e.insertBefore(g,c.head);
a=7==h["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,a);var c=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),e=CANVAS_WIDTH*c;c*=CANVAS_HEIGHT;if(c<a){var g=a-c;c+=g;e+=CANVAS_WIDTH/CANVAS_HEIGHT*g}else e<d&&(g=d-e,e+=g,c+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=a/2-c/2;var h=d/2-e/2,b=CANVAS_WIDTH/e;if(h*b<-EDGEBOARD_X||g*b<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,g=(a-c)/2,h=(d-e)/2,b=CANVAS_WIDTH/e;s_iOffsetX=-1*h*b;s_iOffsetY=-1*g*b;0<=g&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);window.s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*e,s_oStage.canvas.height=2*c,canvas.style.width=e+"px",canvas.style.height=c+"px",s_iScaleFactor=
2*Math.min(e/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor):s_bMobile||isChrome()?($("#canvas").css("width",e+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=e,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(e/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(a,d,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(d),s_aSounds[a].loop(c),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(d)}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(d)}
function fadeSound(a,d,c,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].fade(d,c,e)}function soundPlaying(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)return s_aSounds[a].playing()}function createBitmap(a,d,c){var e=new createjs.Bitmap(a),g=new createjs.Shape;d&&c?g.graphics.beginFill("#fff").drawRect(0,0,d,c):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=g;return e}
function createSprite(a,d,c,e,g,h){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-c,-e,g,h);a.hitArea=d;return a}function pad(a,d,c){a+="";return a.length>=d?a:Array(d-a.length+1).join(c||"0")+a}function randomFloatBetween(a,d,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(c))}
function rotateVector2D(a,d){var c=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),e=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(c,e)}function tweenVectorsOnX(a,d,c){return a+c*(d-a)}function shuffle(a){for(var d=a.length,c,e;0!==d;)e=Math.floor(Math.random()*d),--d,c=a[d],a[d]=a[e],a[e]=c;return a}function bubbleSort(a){do{var d=!1;for(var c=0;c<a.length-1;c++)a[c]>a[c+1]&&(d=a[c],a[c]=a[c+1],a[c+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}
function easeLinear(a,d,c,e){return c*a/e+d}function easeInQuad(a,d,c,e){return c*(a/=e)*a+d}function easeInSine(a,d,c,e){return-c*Math.cos(a/e*(Math.PI/2))+c+d}function easeInCubic(a,d,c,e){return c*(a/=e)*a*a+d}function getTrajectoryPoint(a,d){var c=new createjs.Point,e=(1-a)*(1-a),g=a*a;c.x=e*d.start.x+2*(1-a)*a*d.traj.x+g*d.end.x;c.y=e*d.start.y+2*(1-a)*a*d.traj.y+g*d.end.y;return c}
function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var c="";c=10>d?c+("0"+d+":"):c+(d+":");return 10>a?c+("0"+a):c+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,d){var c=getBounds(a,.9);var e=getBounds(d,.98);return calculateIntersection(c,e)}
function calculateIntersection(a,d){var c,e,g,h;var b=a.x+(c=a.width/2);var f=a.y+(e=a.height/2);var l=d.x+(g=d.width/2);var k=d.y+(h=d.height/2);b=Math.abs(b-l)-(c+g);f=Math.abs(f-k)-(e+h);return 0>b&&0>f?(b=Math.min(Math.min(a.width,d.width),-b),f=Math.min(Math.min(a.height,d.height),-f),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:f,rect1:a,rect2:d}):null}
function getBounds(a,d){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var e=a.children,g=e.length,h;for(h=0;h<g;h++){var b=getBounds(e[h],1);b.x<c.x&&(c.x=b.x);b.y<c.y&&(c.y=b.y);b.x+b.width>c.x2&&(c.x2=b.x+b.width);b.y+b.height>c.y2&&(c.y2=b.y+b.height)}Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{if(a instanceof createjs.Bitmap){g=
a.sourceRect||a.image;h=g.width*d;var f=g.height*d}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){g=a.spriteSheet.getFrame(a.currentFrame);h=g.rect.width;f=g.rect.height;e=g.regX;var l=g.regY}else c.x=a.x||0,c.y=a.y||0;else c.x=a.x||0,c.y=a.y||0;e=e||0;h=h||0;l=l||0;f=f||0;c.regX=e;c.regY=l;g=a.localToGlobal(0-e,0-l);b=a.localToGlobal(h-e,f-l);h=a.localToGlobal(h-e,0-l);e=a.localToGlobal(0-e,f-l);c.x=
Math.min(Math.min(Math.min(g.x,b.x),h.x),e.x);c.y=Math.min(Math.min(Math.min(g.y,b.y),h.y),e.y);c.width=Math.max(Math.max(Math.max(g.x,b.x),h.x),e.x)-c.x;c.height=Math.max(Math.max(Math.max(g.y,b.y),h.y),e.y)-c.y}return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,c,e;0<d;)e=Math.floor(Math.random()*d),d--,c=a[d],a[d]=a[e],a[e]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),c=0;c<d.length;c++){var e=d[c].split("=");if(e[0]==a)return e[1]}}String.prototype.format=function(){for(var a=this,d=arguments.length;d--;)a=a.replace(new RegExp("\\{"+d+"\\}","gm"),arguments[d]);return a};
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),window.s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();window.s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a,d,c,e,g,h;this.init=function(b,f,l){c=d=0;e=b;g=f;h=l;a={}};this.addSprite=function(b,f){a.hasOwnProperty(b)||(a[b]={szPath:f,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(h)};this._onSpriteLoaded=function(){e.call(h);++c==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=1920,EDGEBOARD_X=150,EDGEBOARD_Y=200,GAME_NAME="plinko",PRIMARY_FONT="impact",FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,BOARD_ROW=13,BOARD_COL=7,BALL_RADIUS,NUM_INSERT_TUBE,CELL_SIZE=140,CELL_PIVOT_FROM_CENTER=90,BALL_FALL_MAX_ANGLE=.5,BALL_FALL_MAX_ROTATION=80,BALL_FALL_ROTATION_ATTENUATION_FACTOR=20,BALL_FALL_SPEED_INCREASE=
.75,BALL_FALL_MAX_SPEED_LIMIT=500,BASKET_LIT_ITERATION=10,PRIZE,PRIZE_PROBABILITY,START_CREDIT=0,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,AD_SHOW_COUNTER,TEXT_PRELOADER_CONTINUE="START",TEXT_PRELOADER_LOGIN="LOGIN",TEXT_GAMEOVER="I'M SORRY, NO MORE CREDITS TO PLAY",TEXT_ARE_SURE="ARE YOU SURE?",TEXT_PLUS="+",TEXT_MIN="-",TEXT_CURRENCY="",TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",
TEXT_SHARE_SHARE1="My score is ",TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,c,e,g,h,b;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();b=new createjs.Container;s_oStage.addChild(b)};this.unload=function(){b.removeAllChildren();(void 0).unload()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var f=
new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.addChild(f);f=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(f);e.x=CANVAS_WIDTH/2-f.width/2;e.y=CANVAS_HEIGHT/2+50;b.addChild(e);a=f.width;d=f.height;g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,1,d);b.addChild(g);e.mask=g;c=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+100;c.textBaseline="alphabetic";c.textAlign="center";
b.addChild(c);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);b.removeChild(h)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(b){c.text=b+"%";100===b&&(c.visible=!1,e.visible=!1,s_oMain.gotoGame());g.graphics.clear();b=Math.floor(b*a/100);g.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,b,d)};this._init()}
function CMain(a){var d,c=0,e=0,g=STATE_LOADING,h,b;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!0;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(FPS),$("body").on("contextmenu","#canvas",function(b){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){c++;h.refreshLoader(Math.floor(c/e*100))};this._initSounds=function(){var b=[];b.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});b.push({path:"./sounds/",filename:"press_button",loop:!1,volume:1,ingamename:"click"});b.push({path:"./sounds/",
filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});b.push({path:"./sounds/",filename:"ball_collision",loop:!1,volume:1,ingamename:"ball_collision"});b.push({path:"./sounds/",filename:"ball_in_basket",loop:!1,volume:1,ingamename:"ball_in_basket"});b.push({path:"./sounds/",filename:"ball_in_basket_negative",loop:!1,volume:1,ingamename:"ball_in_basket_negative"});e+=b.length;s_aSounds=[];for(var a=0;a<b.length;a++)s_aSounds[b[a].ingamename]=new Howl({src:[b[a].path+b[a].filename+".mp3"],
autoplay:!1,preload:!0,loop:b[a].loop,volume:b[a].volume,onload:s_oMain.soundLoaded})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("credits_panel","./sprites/credits_panel.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");
s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("side_right","./sprites/side_right.png");s_oSpriteLibrary.addSprite("side_left","./sprites/side_left.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");
s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_settings","./sprites/but_settings.png");s_oSpriteLibrary.addSprite("but_plus","./sprites/but_plus.png");s_oSpriteLibrary.addSprite("bet_panel","./sprites/bet_panel.png");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("stake","./sprites/stake.png");s_oSpriteLibrary.addSprite("ball_generator","./sprites/ball_generator.png");
s_oSpriteLibrary.addSprite("holes_occluder","./sprites/holes_occluder.png");s_oSpriteLibrary.addSprite("hole_board_occluder","./sprites/hole_board_occluder.png");s_oSpriteLibrary.addSprite("basket_display","./sprites/basket_display.jpg");s_oSpriteLibrary.addSprite("hand_anim","./sprites/hand_anim.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;h.refreshLoader(Math.floor(c/e*100))};this._onAllImagesLoaded=function(){};this._onRemovePreloader=
function(){h.unload();s_oSoundtrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoGame=function(){b=new CGame(f);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=
!1;$("#block_game").css("display","none");s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==d){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&b.update();s_oStage.update(a)}};s_oMain=this;var f=a;ENABLE_CREDITS=a.show_credits;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_aSounds=[],s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oCanvas;
function CTextButton(a,d,c,e,g,h,b,f,l){var k,m,n,r,t,u,p,v,x,z;this._init=function(b,a,c,f,l,d,e,g,h){k=!1;t=[];u=[];z=createBitmap(c);var m=Math.ceil(e/20);x=new createjs.Text(f,"bold "+e+"px "+l,"#000000");x.textAlign="center";x.textBaseline="alphabetic";var n=x.getBounds();x.x=c.width/2+m;x.y=Math.floor(c.height/2)+n.height/3+m-7;v=new createjs.Text(f,"bold "+e+"px "+l,d);v.textAlign="center";v.textBaseline="alphabetic";n=v.getBounds();v.x=c.width/2;v.y=Math.floor(c.height/2)+n.height/3-7;p=new createjs.Container;
p.x=b;p.y=a;p.regX=c.width/2;p.regY=c.height/2;p.cursor="pointer";g||(b=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),z=createSprite(b,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),x.x=m,x.y=m+17,v.x=0,v.y=17,p.regX=0,p.regY=0);p.addChild(z,x,v);h.addChild(p);this._initListener()};this.unload=function(){s_bMobile?p.off("mousedown",m):(p.off("mousedown",m),p.off("mouseover",r));
p.off("pressup",n);l.removeChild(p)};this.setVisible=function(b){p.visible=b};this.setClickable=function(b){k=!b;b||(p.cursor="arrow")};this._initListener=function(){s_bMobile?m=p.on("mousedown",this.buttonDown):(m=p.on("mousedown",this.buttonDown),r=p.on("mouseover",this.buttonOver));n=p.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){t[b]=a;u[b]=c};this.buttonRelease=function(){k||(p.scaleX=1,p.scaleY=1,t[ON_MOUSE_UP]&&t[ON_MOUSE_UP].call(u[ON_MOUSE_UP]))};this.buttonDown=
function(){k||(p.scaleX=.9,p.scaleY=.9,playSound("click",1,!1),t[ON_MOUSE_DOWN]&&t[ON_MOUSE_DOWN].call(u[ON_MOUSE_DOWN]))};this.buttonOver=function(b){s_bMobile||k||(b.target.cursor="pointer")};this.enable=function(){k=!1;f||z.gotoAndStop("state_true")};this.disable=function(){k=!0;f||z.gotoAndStop("state_false")};this.fadeOut=function(){this.setClickable(!1);createjs.Tween.get(p).to({alpha:0},500)};this.fadeIn=function(){this.setClickable(!0);createjs.Tween.get(p).to({alpha:1},500)};this.hideShadow=
function(){x.visible=!1};this.setTextPosition=function(a,c){var f=Math.ceil(b/20);x.x=a+f;x.y=c+f;v.x=a;v.y=c};this.setTextHeight=function(a){x.y=a+Math.ceil(b/20);v.y=a};this.setPosition=function(b,a){p.x=b;p.y=a};this.setX=function(b){p.x=b};this.setY=function(b){p.y=b};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this._init(a,d,c,e,g,h,b,f,l);return this}
function CToggle(a,d,c,e,g){var h,b,f,l,k,m,n;this._init=function(b,a,c,f,l){k=[];m=[];var d=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=f;n=createSprite(d,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);n.x=b;n.y=a;n.stop();l.addChild(n);this._initListener()};this.unload=function(){s_bMobile?n.off("mousedown",b):(n.off("mousedown",b),n.off("mouseover",l));n.off("pressup",f);n.parent.removeChild(n)};
this._initListener=function(){s_bMobile?b=n.on("mousedown",this.buttonDown):(b=n.on("mousedown",this.buttonDown),l=n.on("mouseover",this.buttonOver));f=n.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){k[b]=a;m[b]=c};this.setActive=function(b){h=b;n.gotoAndStop("state_"+h)};this.buttonRelease=function(){n.scaleX=1;n.scaleY=1;playSound("click",1,!1);h=!h;n.gotoAndStop("state_"+h);k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(m[ON_MOUSE_UP],h)};this.buttonDown=function(){n.scaleX=.9;n.scaleY=
.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.buttonOver=function(b){s_bMobile||(b.target.cursor="pointer")};this.setPosition=function(b,a){n.x=b;n.y=a};this.getButtonImage=function(){return n};this._init(a,d,c,e,g)}
function CGfxButton(a,d,c,e){var g,h,b,f,l=[],k,m,n,r,t;this._init=function(a,c,l,d){g=!1;h=1;b=[];f=[];k=new createjs.Container;k.x=a;k.y=c;k.scaleX=k.scaleY=h;d.addChild(k);m=createBitmap(l);m.regX=l.width/2;m.regY=l.height/2;k.addChild(m);this._initListener()};this.unload=function(){s_bMobile?k.off("mousedown",n):(k.off("mousedown",n),k.off("mouseover",t));k.off("pressup",r);k.parent.removeChild(k)};this.setVisible=function(b){k.visible=b};this.setClickable=function(b){g=!b};this._initListener=
function(){s_bMobile?n=k.on("mousedown",this.buttonDown):(n=k.on("mousedown",this.buttonDown),t=k.on("mouseover",this.buttonOver));r=k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,k){b[a]=c;f[a]=k};this.addEventListenerWithParams=function(a,c,k,d){b[a]=c;f[a]=k;l=d};this.buttonRelease=function(){g||(k.scaleX=h,k.scaleY=h,b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(f[ON_MOUSE_UP],l))};this.buttonDown=function(){g||(k.scaleX=.9*h,k.scaleY=.9*h,playSound("click",1,!1),b[ON_MOUSE_DOWN]&&
b[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],l))};this.buttonOver=function(b){s_bMobile||g||(b.target.cursor="pointer")};this.addText=function(b){b=new createjs.Text(b," 50px "+PRIMARY_FONT,"#ffffff");b.textAlign="center";b.textBaseline="middle";b.lineWidth=200;k.addChild(b)};this.pulseAnimation=function(){createjs.Tween.get(k).to({scaleX:1.1*h,scaleY:1.1*h},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:h},650,createjs.Ease.quadIn).call(function(){u.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(k).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){u.trebleAnimation()})};this.setPosition=function(b,a){k.x=b;k.y=a};this.setX=function(b){k.x=b};this.setY=function(b){k.y=b};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this.getPos=function(){return{x:k.x,y:k.y}};var u=this;this._init(a,d,c,e);return this}
function CGame(a){var d,c,e,g,h,b,f,l,k,m,n,r,t,u,p=null;this._init=function(){setVolume("soundtrack",.3);c=START_BET;e=START_CREDIT.toFixed(2)/1;g=BANK_CASH;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);m=new createjs.Container;s_oStage.addChild(m);n=new createjs.Container;s_oStage.addChild(n);r=new createjs.Container;s_oStage.addChild(r);t=new createjs.Container;s_oStage.addChild(t);this._setBoard();NUM_INSERT_TUBE=u[0].length;a=s_oSpriteLibrary.getSprite("side_left");
a=createBitmap(a);a.x=100;t.addChild(a);a=s_oSpriteLibrary.getSprite("side_right");var d=createBitmap(a);d.regX=a.width;d.x=CANVAS_WIDTH-100;t.addChild(d);BALL_RADIUS=s_oSpriteLibrary.getSprite("ball").height/2;f=new CBallGenerator(r);l=new CInsertTubeController(r);k=new CScoreBasketController(m);this._initProbability();b=new CInterface(m);l.showSlots();$(s_oMain).trigger("start_level",1)};this._setBoard=function(){var b=BOARD_ROW,a=BOARD_COL;u=[];for(var c=0;c<b;c++){u[c]=[];for(var f=0;f<a-(c+1)%
2;f++)u[c][f]=new CCell(0===c%2?f*CELL_SIZE:-CELL_SIZE/2+f*CELL_SIZE,c*CELL_SIZE/2,n,c,f),c!==BOARD_ROW-1&&(1!==c%2||0!==f&&f!==BOARD_COL-1)||u[c][f].removeStake()}n.regX=n.getBounds().x+n.getBounds().width/2;n.regY=n.getBounds().y+n.getBounds().height/2;n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2-29;new CGridMapping(u)};this._initProbability=function(){h=[];for(var b=0;b<PRIZE_PROBABILITY.length;b++)for(var a=0;a<PRIZE_PROBABILITY[b];a++)h.push(b)};this.launch=function(a){window.server_launch||(window.server_launch=
!0,d=a,b.hideControls(),l.hideSlots(),userBetSend(c,this.launchRs))};this.launchRs=function(a){window.server_launch&&(window.server_launch=!1,server_iEndCol=a,-1==a?(b.showControls(),l.showSlots()):this.launch2(d))};this.launch2=function(b){this._placeBet();this.setBall();l.hideSlots();f.shiftBallAnimation();b=s_oGame.getBallPivotCellPos(0,b);p.launchAnim(b)};this.updateCredit=function(a,c){e=a;c&&b.refreshCredit(e.toFixed(2)/1)};this._placeBet=function(){b.hideControls()};this.setBall=function(){p=
f.getNextBall();var b=p.getPos();b=n.globalToLocal(b.x*s_iScaleFactor,b.y*s_iScaleFactor);n.addChild(p.getSprite());p.setPos(b)};this.getFallPath=function(){var b=0<=window.server_iEndCol?server_iEndCol:this._setEndCol();b=s_oGridMapping.getRandomPathFromColToCol(d,b);for(var a=0;a<b.length;a++)u[b[a].row][b[a].col].highlight(!0);b=this.getPathCopy(b);p.startPathAnim(b,500);p=null};this.ballArrived=function(a){PRIZE[a]?playSound("ball_in_basket",1,!1):playSound("ball_in_basket_negative",1,!1);k.litBasket(a,
PRIZE[a]);g-=PRIZE[a];$(s_oMain).trigger("save_score",[e]);l.showSlots();b.showControls();b.refreshCredit(e.toFixed(2)/1);this.checkEndGame()};this.checkEndGame=function(){c>e&&(c=Math.floor(e),b.refreshBet(c));c>game_MaxBet_newTRX&&(c=game_MaxBet_newTRX,b.refreshBet(c))};this.modifyBonus=function(a){"plus"===a?c+=5:c-=5;c>game_MaxBet_newTRX?c=game_MaxBet_newTRX:0>c&&(c=0);c>e&&(c=Math.floor(e));b.refreshBet(c)};this._setEndCol=function(){for(var b,a=[],c=0;c<h.length;c++)b=PRIZE[h[c]],b<=g&&a.push({prize:b,
index:c});return h[a[Math.floor(Math.random()*a.length)].index]};this.getBall=function(){return p};this.getBoard=function(){return u};this.getBallPivotCellPos=function(b,a){return u[b][a].getCenterOfBallOnPivot()};this.getPathCopy=function(b){for(var a=[],c=0;c<b.length;c++)a.push(b[c]);return a};this.unload=function(){b.unload();k.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){setVolume("soundtrack",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("end_level",
1);s_oGame.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){};this.gameOver=function(){b.hideControls()};this.getSlotPosition=function(b){return l.getSlotPos(b)};this.sortChildren=function(b,a,c){return b.y<a.y?1:b.y>a.y?-1:0};this.update=function(){n.sortChildren(this.sortChildren)};s_oGame=this;START_BET=a.start_bet;MAX_MULTIPLIER=a.max_multiplier;BANK_CASH=a.bank_cash;PRIZE=a.prize;PRIZE_PROBABILITY=a.prize_probability;AD_SHOW_COUNTER=a.ad_show_counter;this._init()}var s_oGame;
function CInterface(a){var d,c,e,g,h,b,f,l,k,m,n,r,t,u,p,v,x=null,z=null;this._init=function(a){var q=s_oSpriteLibrary.getSprite("hand_anim"),y=q.width/6,w=q.height/4;q=new createjs.SpriteSheet({framerate:20,images:[q],frames:[[1,1,256,230,0,0,0],[259,1,256,230,0,0,0],[517,1,256,230,0,0,0],[775,1,256,230,0,0,0],[1033,1,256,230,0,0,0],[1291,1,256,230,0,0,0],[1,233,256,230,0,0,0],[259,233,256,230,0,0,0],[517,233,256,230,0,0,0],[775,233,256,230,0,0,0],[1033,233,256,230,0,0,0],[1291,233,256,230,0,0,0],
[1,465,256,230,0,0,0],[259,465,256,230,0,0,0],[517,465,256,230,0,0,0],[775,465,256,230,0,0,0],[1033,465,256,230,0,0,0],[1291,465,256,230,0,0,0],[1,697,256,230,0,0,0],[259,697,256,230,0,0,0],[517,697,256,230,0,0,0],[775,697,256,230,0,0,0]],animations:{idle:[0,21]}});n=0;v=createSprite(q,"idle",y/2,w/2,y,w);q=s_oGame.getSlotPosition(n);v.x=q.x;v.y=q.y;v.regX=y/2-30;v.regY=w/2;v.on("animationend",this._moveHand);s_oStage.addChild(v);q=s_oSpriteLibrary.getSprite("but_credits");h=CANVAS_WIDTH-q.width/
2-10;b=q.height/2+10;l=new CGfxButton(h,b,q,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);e=y=h-q.width-10;g=q.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),f=new CToggle(e,g,q,s_bAudioActive,s_oStage),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),y=e-q.width/2-10;q=window.document;w=q.documentElement;x=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;z=q.exitFullscreen||q.mozCancelFullScreen||
q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(x=!1);x&&screenfull.enabled&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),d=y,c=q.height/2+10,k=new CToggle(d,c,q,s_bFullscreen,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));y=new createjs.Container;y.x=854;y.y=1650;a.addChild(y);q=s_oSpriteLibrary.getSprite("bet_panel");w=createBitmap(q);w.regX=q.width/2;w.regY=q.height/2;y.addChild(w);r=new createjs.Text(TEXT_CURRENCY+START_BET.toFixed(2)," 40px "+
PRIMARY_FONT,"#ffffff");r.x=w.x;r.y=w.y-2;r.textAlign="center";r.textBaseline="middle";r.lineWidth=400;y.addChild(r);q=s_oSpriteLibrary.getSprite("but_plus");t=new CTextButton(160,0,q,TEXT_PLUS,PRIMARY_FONT,"#0083ea",80,!1,y);t.enable();t.addEventListener(ON_MOUSE_UP,this._onButPlusRelease,this);t.setTextPosition(1,26);t.hideShadow();q=s_oSpriteLibrary.getSprite("but_plus");u=new CTextButton(-160,0,q,TEXT_MIN,PRIMARY_FONT,"#0083ea",80,!1,y);u.enable();u.addEventListener(ON_MOUSE_UP,this._onButMinRelease,
this);u.setTextPosition(2,26);u.hideShadow();q=s_oSpriteLibrary.getSprite("credits_panel");w=createBitmap(q);w.regX=q.width/2;w.regY=q.height/2;w.x=332;w.y=y.y;a.addChild(w);p=new createjs.Text(TEXT_CURRENCY+START_CREDIT.toFixed(2)," 36px "+PRIMARY_FONT,"#ffffff");p.x=w.x;p.y=w.y;p.textAlign="center";p.textBaseline="middle";p.lineWidth=400;a.addChild(p);q=s_oSpriteLibrary.getSprite("but_settings");m=new CGUIExpandible(h,b,q,s_oStage);m.addButton(l);m.addButton(f);x&&screenfull.enabled&&m.addButton(k);
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;l.unload();x&&screenfull.enabled&&k.unload();u.unload();t.unload();m.unload();s_oInterface=null};this.refreshButtonPos=function(b,a){m.refreshPos(b,a)};this.refreshBet=function(b){r.text=TEXT_CURRENCY+b.toFixed(2)};this.refreshCredit=function(b){p.text=TEXT_CURRENCY+b.toFixed(2)};this._onButPlusRelease=function(){s_oGame.modifyBonus("plus")};this._onButMinRelease=function(){s_oGame.modifyBonus("min")};
this.hideControls=function(){u.setVisible(!1);t.setVisible(!1);this.setHelpVisible(!1)};this.showControls=function(){u.setVisible(!0);t.setVisible(!0);this.setHelpVisible(!0)};this.setHelpVisible=function(b){(v.visible=b)&&v.gotoAndPlay("idle")};this._moveHand=function(){n++;n===NUM_INSERT_TUBE&&(n=0);var b=s_oGame.getSlotPosition(n);v.x=b.x;v.y=b.y};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){$("#contractModal").modal("show")};
this.resetFullscreenBut=function(){x&&screenfull.enabled&&k.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?z.call(window.document):x.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CAreYouSurePanel(a,d){var c,e,g,h,b,f;this._init=function(a,d){h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;f=h.on("mousedown",function(){});s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var k=s_oSpriteLibrary.getSprite("msg_box"),l=createBitmap(k);l.regX=k.width/2;l.regY=k.height/2;b.addChild(l);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+k.height/2;c=b.y;createjs.Tween.get(b).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);l=new createjs.Text(TEXT_ARE_SURE," 60px "+PRIMARY_FONT,"#ffffff");l.y=-k.height/2+160;l.textAlign="center";l.textBaseline="middle";l.lineWidth=400;b.addChild(l);e=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_yes"),b);e.addEventListener(ON_MOUSE_UP,this._onButYes,this);g=new CGfxButton(-110,80,s_oSpriteLibrary.getSprite("but_no"),b);g.addEventListener(ON_MOUSE_UP,this._onButNo,this);g.pulseAnimation()};this._onButYes=function(){g.setClickable(!1);e.setClickable(!1);
createjs.Tween.get(h).to({alpha:0},500);createjs.Tween.get(b).to({y:c},400,createjs.Ease.backIn).call(function(){l.unload();a&&a()})};this._onButNo=function(){g.setClickable(!1);e.setClickable(!1);createjs.Tween.get(h).to({alpha:0},500);createjs.Tween.get(b).to({y:c},400,createjs.Ease.backIn).call(function(){l.unload();d&&d()})};this.unload=function(){g.unload();e.unload();s_oStage.removeChild(h);s_oStage.removeChild(b);h.off("mousedown",f)};var l=this;this._init(a,d)}
var DIR_TOPRIGHT="DIR_TOPRIGHT",DIR_BOTRIGHT="DIR_BOTRIGHT",DIR_TOPLEFT="DIR_TOPLEFT",DIR_BOTLEFT="DIR_BOTLEFT",DIR_SELF="DIR_SELF";
function CGridMapping(a){var d,c,e,g,h;this._init=function(b){d=BOARD_ROW;c=BOARD_COL;g=[];e=[];for(var a=0;a<b.length;a++){e[a]=[];for(var l=0;l<b[a].length;l++)e[a][l]=[]}this._buildMap();h=[];for(a=0;a<b[0].length;a++)h[a]=this.getAllPathFrom({row:0,col:a})};this._buildMap=function(){for(var b=0;b<a.length;b++)for(var c=0;c<a[b].length;c++)e[b][c][DIR_BOTRIGHT]=this._setNeighbor(b,c,DIR_BOTRIGHT),e[b][c][DIR_BOTLEFT]=this._setNeighbor(b,c,DIR_BOTLEFT),e[b][c][DIR_SELF]=this._setNeighbor(b,c,DIR_SELF)};
this._setNeighbor=function(b,a,l){var f=null;switch(l){case DIR_TOPRIGHT:0<b&&a<c-b%2&&(f={row:b-1,col:a+(b+1)%2});break;case DIR_BOTRIGHT:b<d-1&&a+b%2<c&&(f={row:b+1,col:a+(b+1)%2});break;case DIR_TOPLEFT:0<b&&0<=a-(b-1)%2&&(f={row:b-1,col:a-(b+1)%2});break;case DIR_BOTLEFT:b<d-1&&a>=b%2&&(f={row:b+1,col:a-b%2});break;case DIR_SELF:f={row:b,col:a}}return f};this._getNeighborByDir=function(b,a,c){return e[b][a][c]};this._getAllNeighbor=function(b,a){var c=[],f;for(f in e[b][a])null!==e[b][a][f]&&
c.push(e[b][a][f]);return c};this._getMainDiagonal=function(b,a,c){var f=[],d=c[b][a].getColor();this._findInDirection(b,a,DIR_BOTRIGHT,f,99,d,c);this._findInDirection(b,a,DIR_TOPLEFT,f,99,d,c);return f};this._getSecondDiagonal=function(b,a,c){var f=[],d=c[b][a].getColor();this._findInDirection(b,a,DIR_BOTLEFT,f,99,d,c);this._findInDirection(b,a,DIR_TOPRIGHT,f,99,d,c);return f};this._getRow=function(b,a,c){var f=[],d=c[b][a].getColor();this._findInDirection(b,a,DIR_LEFT,f,99,d,c);this._findInDirection(b,
a,DIR_RIGHT,f,99,d,c);return f};this._getCol=function(b,a,c){var f=[],d=c[b][a].getColor();this._findInDirection(b,a,DIR_TOP,f,99,d,c);this._findInDirection(b,a,DIR_BOT,f,99,d,c);return f};this._getStraightByDirAndRadius=function(a,c,d,k,e){var b=[];g=[];g.push({radius:k,direction:null});var f=e[a][c].getColor();this._findInDirection(a,c,d,b,k,f,e);return b};this._getStraightRowByRadius=function(a,c,d){var b=[];g=[];g.push({radius:d,direction:null});this._findInDirection(a,c,DIR_LEFT,b,d);this._findInDirection(a,
c,DIR_RIGHT,b,d);return b};this._getStraightColByRadius=function(a,c,d){var b=[];g=[];g.push({radius:d,direction:null});this._findInDirection(a,c,DIR_TOP,b,d);this._findInDirection(a,c,DIR_BOT,b,d);return b};this._findInDirection=function(a,c,d,k,h,n,r){--h;if(null!==e[a][c][d]&&0<=h){var b=e[a][c][d].row;a=e[a][c][d].col;n?(c=r[b][a].getColor(),c!==n&&(null===c?(k.push({row:b,col:a}),g.push({radius:h,direction:d}),this._findInDirection(b,a,d,k,h,n,r)):(k.push({row:b,col:a}),g.push({radius:h,direction:d})))):
(k.push({row:b,col:a}),g.push({radius:h,direction:d}),this._findInDirection(b,a,d,k,h,n,r))}};this.getAllPathFrom=function(a){return this._findAllPathDFS(e[a.row][a.col],[],[])};this.getRandomPathFrom=function(a){a=s_oGridMapping.getAllPathFrom(a);var b=[];0<a.length&&(b=a[Math.floor(Math.random()*(a.length-1))]);return b};this.getAllPathFromTo=function(a,c){for(var b=s_oGridMapping.getAllPathFrom(a),d=b.length-1;0<=d;d--){for(var f=!1,e=0;e<b[d].length;e++)if(b[d][e].row===c.row&&b[d][e].col===c.col){f=
!0;break}f||b.splice(d,1)}return b};this.getRandomPathFromTo=function(a,c){var b=s_oGridMapping.getAllPathFromTo(a,c),d=[];0<b.length&&(d=b[Math.floor(Math.random()*(b.length-1))]);return d};this.getRandomPathFromCol=function(a){a=h[a];return a[Math.floor(Math.random()*(a.length-1))]};this.getRandomPathFromColToCol=function(a,c){for(var b=[],d=e.length-1,f=0;f<h[a].length;f++){var g=h[a][f];g[d].col===c&&b.push(g)}d=[];0<b.length&&(d=b[Math.floor(Math.random()*(b.length-1))]);return d};this._findAllPathDFS=
function(a,c,d){c=c.slice(0);var b=0,f=this._getChildren(a),e=f.length;c.push(a[DIR_SELF]);if(0===e)return d.push(c),d;for(b;b<e;b++)this._findAllPathDFS(f[b],c,d);return d};this._getChildren=function(a){var b=[],c;for(c in a)null===a[c]||c!==DIR_BOTLEFT&&c!==DIR_BOTRIGHT||b.push(e[a[c].row][a[c].col]);return b};this._init(a);s_oGridMapping=this}var s_oGridMapping;
function CCell(a,d,c,e,g,h){var b,f,l;this._init=function(a,c,d,e,g,h){b=new createjs.Container;b.x=a;b.y=c;b.alpha=0;d.addChild(b);f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.51)").drawRect(-50,-50,100,100);f.visible=!1;f.rotation=45;b.addChild(f);e=s_oSpriteLibrary.getSprite("stake");l=createBitmap(e);l.regX=e.width/2;l.x=a;l.y=c+60;d.addChild(l)};this.unload=function(){c.removeChild(b)};this.getCenterPos=function(){return{x:a,y:d}};this.getPivotPos=function(){return{x:a,y:d+CELL_PIVOT_FROM_CENTER}};
this.getCenterOfBallOnPivot=function(){return{x:a,y:d+CELL_PIVOT_FROM_CENTER-BALL_RADIUS}};this.checkBallOverlap=function(b){var c=b.x-a;b=b.y-d;return c*c+b*b<BALL_RADIUS*BALL_RADIUS};this.removeStake=function(){l.visible=!1};this.highlight=function(a){f.visible=a};this._debug=function(){b.alpha=1;var a=new createjs.Text(e+","+g,"bold 30px Arial","#000000");a.textAlign="center";a.textBaseline="middle";a.lineWidth=200;a.outline=4;b.addChild(a);var c=new createjs.Text(a.text,"bold 30px Arial","#ffffff");
c.textAlign=a.textAlign;c.textBaseline=a.textBaseline;c.lineWidth=a.lineWidth;b.addChild(c)};this._init(a,d,c,e,g,h)}
function CBall(a,d){var c,e,g,h;this._init=function(a,b){g=new createjs.Container;g.x=a.x;g.y=a.y;b.addChild(g);var d=s_oSpriteLibrary.getSprite("ball");h=createBitmap(d);h.regX=d.width/2;h.regY=d.height/2;g.addChild(h);c=d.height};this.unload=function(){g.parent.removeChild(g)};this.getPos=function(){return{x:g.x,y:g.y}};this.getSprite=function(){return g};this.resetPos=function(){g.x=a.x;g.y=a.y};this.setPos=function(a){g.x=a.x;g.y=a.y};this.setPosToPivot=function(){g.regY=c/2};this._getFallParams=
function(a,b){var c=s_oGame.getBallPivotCellPos(a[0].row,a[0].col);if(1<a.length)if(s_oGame.getBallPivotCellPos(a[1].row,a[1].col).x>c.x){var d=Math.random()*BALL_FALL_MAX_ANGLE;var f="right"}else d=-Math.random()*BALL_FALL_MAX_ANGLE,f="left";else d=-BALL_FALL_MAX_ANGLE+Math.random()*BALL_FALL_MAX_ANGLE*2,f="right";var l=new CVector2(0,-BALL_RADIUS);rotateVector2D(d,l);l.subtract(new CVector2(0,-BALL_RADIUS));var t=c.x-l.getX();l=c.y+l.getY();d*=BALL_FALL_ROTATION_ATTENUATION_FACTOR;c=c.x>g.x?h.rotation+
BALL_FALL_MAX_ROTATION-d:h.rotation-BALL_FALL_MAX_ROTATION-d;(g.x<t?"right":"left")===f?(f=b*BALL_FALL_SPEED_INCREASE,f<BALL_FALL_MAX_SPEED_LIMIT&&(f=BALL_FALL_MAX_SPEED_LIMIT)):f=e;return{rotation:c,posx:t,posy:l,newtime:f}};this.launchAnim=function(a){createjs.Tween.get(g).to({x:a.x},1E3,createjs.Ease.sineOut);createjs.Tween.get(g).to({y:a.y-400},500,createjs.Ease.cubicOut).to({y:a.y},500,createjs.Ease.cubicIn).call(function(){s_oGame.getFallPath()})};this.startPathAnim=function(a,b){e=b;this._jumpBall(a,
b)};this._jumpBall=function(a,c){playSound("ball_collision",1,!1);var d=a.splice(0,1);if(1===a.length)b._lastJumpBallAnim(a,c);else{d=s_oGame.getBallPivotCellPos(d[0].row,d[0].col);var e=s_oGame.getBallPivotCellPos(a[0].row,a[0].col);createjs.Tween.get(g).to({x:e.x},c);createjs.Tween.get(g).to({y:d.y-10},c/4,createjs.Ease.cubicOut).to({y:e.y},3*c/4,createjs.Ease.cubicIn).call(function(){b._jumpBall(a,c)})}};this._fallBall=function(a,c){a.splice(0,1);if(1===a.length)b._lastFallBallAnim(a,c);else{var d=
this._getFallParams(a,c);createjs.Tween.get(h).to({rotation:d.rotation},c,createjs.Ease.sineIn);createjs.Tween.get(g,{override:!0}).to({x:d.posx},c,createjs.Ease.sineIn);createjs.Tween.get(g).to({y:d.posy},c,createjs.Ease.cubicIn).call(function(){b._fallBall(a,d.newtime)})}};this.releaseBallAnim=function(a){var b=s_oGame.getBoard()[0][a].getCenterOfBallOnPivot();createjs.Tween.get(g).to({y:b.y},500,createjs.Ease.sineIn).call(function(){s_oGame.launchBall(a)})};this._lastFallBallAnim=function(a,b){var c=
this._getFallParams(a,b),d=c.posy+170;createjs.Tween.get(h).to({rotation:c.rotation},b,createjs.Ease.sineIn);createjs.Tween.get(g,{override:!0}).to({x:c.posx},b,createjs.Ease.sineIn);createjs.Tween.get(g).to({y:d},b,createjs.Ease.cubicIn).call(function(){createjs.Tween.get(g).to({y:d-100},b/2,createjs.Ease.cubicOut).to({y:d},b,createjs.Ease.bounceOut);s_oGame.ballArrived(a[0].col)})};this._lastJumpBallAnim=function(a,c){var d=s_oGame.getBallPivotCellPos(a[0].row,a[0].col),e=d.y+220;createjs.Tween.get(g,
{override:!0}).to({x:d.x},c,createjs.Ease.sineIn);createjs.Tween.get(g).to({y:g.y-10},c/4,createjs.Ease.cubicOut).to({y:e},3*c/4,createjs.Ease.cubicIn).call(function(){s_oGame.ballArrived(a[0].col);createjs.Tween.get(g).to({y:e-100},c/2,createjs.Ease.cubicOut).to({y:e},c,createjs.Ease.bounceOut).call(function(){createjs.Tween.get(g).to({alpha:0},3E3,createjs.Ease.cubicIn).call(function(){b.unload()})})})};var b=this;this._init(a,d)}
function CBallGenerator(a){var d,c,e,g,h,b,f;this._init=function(a){b=new createjs.Container;a.addChild(b);f=new createjs.Container;a.addChild(f);e=3;g=2*BALL_RADIUS-20;d=182;c=264;h=[];for(a=0;a<e;a++)h[a]=new CBall({x:d-a*g,y:c},b);a=s_oSpriteLibrary.getSprite("ball_generator");a=createBitmap(a);a.x=0;a.y=196;f.addChild(a)};this.unload=function(){a.removeChild(b);a.removeChild(f)};this.shiftBallAnimation=function(){h.splice(0,1);var a=e-1,f={x:d-a*g,y:c};h[a]=new CBall(f,b);for(a=0;2>a;a++)f={x:d-
a*g,y:c},createjs.Tween.get(h[a].getSprite(),{override:!0}).wait(200*a).to({x:f.x},1E3,createjs.Ease.cubicIn)};this.getNextBall=function(){return h[0]};this._init(a)}
function CInsertTubeController(a){var d,c,e=!1;this._init=function(a){c=new createjs.Container;a.addChild(c);a=s_oSpriteLibrary.getSprite("holes_occluder");var e=createBitmap(a);e.regX=a.width/2;e.regY=a.height/2;e.x=CANVAS_WIDTH/2;e.y=408;c.addChild(e);a=s_oSpriteLibrary.getSprite("hole_board_occluder");e=[];for(var b=0;b<NUM_INSERT_TUBE;b++){e.push({x:288+140*b,y:356});var f=createBitmap(a);f.regX=a.width/2;f.regY=a.height/2;f.x=e[b].x;f.y=e[b].y;c.addChild(f)}d=[];s_oSpriteLibrary.getSprite("bg_number");
for(b=0;b<NUM_INSERT_TUBE;b++)a=new CSlot(e[b].x,e[b].y+20,90,100,c),a.addEventListenerWithParams(ON_MOUSE_UP,this._onSlot,this,b),d.push(a);this.hideSlots()};this.unload=function(){a.removeChild(c)};this.checkBallOverlap=function(a){for(var c,b=0;b<NUM_INSERT_TUBE;b++)if(c=d[b].checkOverlap(a))return{pos:d[b].getPos(),index:b}};this.getSlotPos=function(a){return d[a].getPos()};this.hideSlots=function(){e=!1;for(var a=0;a<NUM_INSERT_TUBE;a++)d[a].setVisible(!1)};this.showSlots=function(){e=!0;for(var a=
0;a<NUM_INSERT_TUBE;a++)d[a].setVisible(!0)};this.isShowSlots=function(){return e};this._onSlot=function(a){s_oGame.launch(a)};this._init(a)}
function CSlot(a,d,c,e,g){var h,b,f,l,k=[],m,n,r,t,u;this._init=function(a,d,g){h=!1;b=1;f=[];l=[];m=new createjs.Container;m.x=a;m.y=d;m.scaleX=m.scaleY=b;g.addChild(m);n=new createjs.Shape;n.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(-c/2,-e/2,c,e);m.addChild(n);this._initListener()};this.unload=function(){s_bMobile?m.off("mousedown",r):(m.off("mousedown",r),m.off("mouseover",u));m.off("pressup",t);m.parent.removeChild(m)};this.setVisible=function(a){m.visible=a};this.setClickable=function(a){h=
!a};this._initListener=function(){s_bMobile?r=m.on("mousedown",this.buttonDown):(r=m.on("mousedown",this.buttonDown),u=m.on("mouseover",this.buttonOver));t=m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;l[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;l[a]=c;k=d};this.buttonRelease=function(){h||(m.scaleX=b,m.scaleY=b,f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(l[ON_MOUSE_UP],k))};this.buttonDown=function(){h||(m.scaleX=.9*b,m.scaleY=.9*b,playSound("click",
1,!1),f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],k))};this.buttonOver=function(a){s_bMobile||h||(a.target.cursor="pointer")};this.addText=function(a){a=new createjs.Text(a," 50px "+PRIMARY_FONT,"#ffffff");a.textAlign="center";a.textBaseline="middle";a.lineWidth=200;m.addChild(a)};this.pulseAnimation=function(){createjs.Tween.get(m).to({scaleX:1.1*b,scaleY:1.1*b},850,createjs.Ease.quadOut).to({scaleX:b,scaleY:b},650,createjs.Ease.quadIn).call(function(){p.pulseAnimation()})};this.trembleAnimation=
function(){createjs.Tween.get(m).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){p.trebleAnimation()})};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this.getPos=function(){return{x:m.x,y:m.y}};var p=this;this._init(a,d,g);return this}
function CScoreBasketController(a){var d;this._init=function(a){var c=new createjs.Container;c.y=1472;a.addChild(c);var g=s_oSpriteLibrary.getSprite("basket_display");a=g.width/4;var h=g.height;g=new createjs.SpriteSheet({images:[g],frames:{width:a,height:h,regX:a/2,regY:h/2},animations:{state_off:[0],state_green:[1],state_yellow:[2],state_red:[3]}});d=[];for(var b=0;b<PRIZE.length;b++)d.push(new CBasket(290+140*b,0,c,g,a,h,PRIZE[b].toString()));this.refreshText()};this.unload=function(){for(var a=
0;a<PRIZE.length;a++)d[a].unload()};this.litBasket=function(a,e){d[a].lit(e)};this.refreshText=function(a){a=1;for(var c=0;c<PRIZE.length;c++)d[c].refreshText(a*PRIZE[c]),d[c].refreshText2(PRIZE_PROBABILITY[c])};this._init(a)}
function CBasket(a,d,c,e,g,h,b){var f,l,k,m;this._init=function(a,b,c,d,e,g,h){k=new createjs.Container;k.y=b;k.x=a;c.addChild(k);a=createSprite(d,"state_off",e/2,g/2,e,g);k.addChild(a);m=createSprite(d,"state_on",e/2,g/2,e,g);m.alpha=0;k.addChild(m);d=this._verticalizeText(h);f=new createjs.Text(d," 40px "+PRIMARY_FONT,"#ffffff");f.textAlign="center";f.textBaseline="middle";f.lineWidth=200;k.addChild(f);_iStartSize2=30;l=new createjs.Text("00%"," "+_iStartSize2+"px "+PRIMARY_FONT,"#ffffff");l.textAlign=
"center";l.textBaseline="middle";l.lineWidth=200;k.addChild(l);l.y=80;this._setText(40)};this.unload=function(){c.removeChild(k)};this.refreshText=function(a){0<a&&(a="x"+a);f.text=a};this.refreshText2=function(a){l.text=a+"%"};this._setText=function(a){for(var b=a;f.getBounds().height>h-a;)b--,f.font=" "+b+"px "+PRIMARY_FONT;f.y=-f.getBounds().height/2+10};this._verticalizeText=function(a){for(var b="",c=0;c<a.length;c++)b=c!==a.length-1?b+(a[c]+"\n"):b+a[c];return b};this.lit=function(a){1>a?m.gotoAndPlay("state_red"):
4>=a?m.gotoAndPlay("state_yellow"):m.gotoAndPlay("state_green");n._recursiveLit(BASKET_LIT_ITERATION)};this._recursiveLit=function(a){a--;0>a||createjs.Tween.get(m).to({alpha:1},100).to({alpha:0},100).call(function(){n._recursiveLit(a)})};var n=this;this._init(a,d,c,e,g,h,b)}
function CGUIExpandible(a,d,c,e){var g,h,b,f,l,k,m,n;this._init=function(a,c,d,e){f=[];k=new createjs.Container;k.x=a;k.y=c;e.addChild(k);m=new createjs.Container;k.addChild(m);n=new createjs.Container;k.addChild(n);b=!1;l=new CGfxButton(0,0,d,n);l.addEventListener(ON_MOUSE_UP,this._onMenu,this);h=g=120};this.unload=function(){l.unload();e.removeChild(k)};this.refreshPos=function(b,c){k.x=a-b;k.y=d+c};this.addButton=function(a){a=a.getButtonImage();a.x=0;a.y=0;a.visible=0;m.addChildAt(a,0);f.push(a)};
this._onMenu=function(){(b=!b)?r._expand():r._collapse()};this._expand=function(){for(var a=0;a<f.length;a++)f[a].visible=!0,createjs.Tween.get(f[a],{override:!0}).wait(300*a/2).to({y:g+a*h},300,createjs.Ease.cubicOut)};this._collapse=function(){for(var a=0;a<f.length;a++){var b=f[f.length-1-a];createjs.Tween.get(b,{override:!0}).wait(300*a/2).to({y:0},300,createjs.Ease.cubicOut).call(function(a){a.visible=!1},[b])}};var r=this;this._init(a,d,c,e)};